### PR TITLE
test/e2e: Skip privileged container test if NoNewPrivs is set

### PR DESCRIPTION
**Pull request by ricardobranco777**
Skip privileged container test if NoNewPrivs is set.

Otherwise the test for https://www.thkukuk.de/blog/no_new_privs/ will fail:
https://openqa.opensuse.org/tests/5575293

#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [ ] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [ ] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [ ] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by ricardobranco777** [comment]
No change needed for bats:
- w/ crun: https://openqa.opensuse.org/tests/5575298
- w/ runc: https://openqa.opensuse.org/tests/5575380

**Comment by baude** [comment]
LGTM. If you end up pushing again, i would love a better commit description on why this is needed for your test environment.  No objections here however.

File: test/e2e/run_privileged_test.go [hunk 1]
```diff
@@ -143,6 +143,11 @@ var _ = Describe("Podman privileged container tests", func() {
 			Skip("Can't determine NoNewPrivs")
 		}
 
+		fields := strings.Fields(cap.OutputToString())
+		if fields[1] != "0" {
+			Skip("NoNewPrivs set")
+		}
```
Comment (Luap99) [inline test/e2e/run_privileged_test.go]: instead of relying of thew output format at all would it not be much cheaper and safer to just query the bool directly instead of the much more expensive fork/execec of grep.

untested:
```
i, err := unix.PrctlRetInt(unix.PR_GET_NO_NEW_PRIVS, 0, 0, 0, 0)
Expect(err).ToNot(HaveOccurred(), "check for NoNewPrivs")
if i == 1 {
	Skip("NoNewPrivs already set")
}
```

Comment (ricardobranco777) [reply test/e2e/run_privileged_test.go]: > instead of relying of thew output format at all would it not be much cheaper and safer to just query the bool directly instead of the much more expensive fork/execec of grep.

It is indeed cheaper but the code is cleaner as is as we're running the same command on the host and the container.

> untested:
> 
> ```
> i, err := unix.PrctlRetInt(unix.PR_GET_NO_NEW_PRIVS, 0, 0, 0, 0)

This snippet alone works.  Does it make sense to modify the PR to change the approach?

Will it compile on non-Linux systems?

Comment (ricardobranco777) [reply test/e2e/run_privileged_test.go]: It doesn't compile on FreeBSD 15-STABLE with go1.25.5 & golang.org/x/sys v0.39.0

```
./testit.go:9:17: undefined: unix.PrctlRetInt
./testit.go:9:34: undefined: unix.PR_GET_NO_NEW_PRIVS
```

```
package main

import (
	"fmt"
	"golang.org/x/sys/unix"
)

func main() {
	val, _ := unix.PrctlRetInt(unix.PR_GET_NO_NEW_PRIVS, 0, 0, 0, 0)
	fmt.Printf("%v\n", val)
}
```

Comment (Luap99) [reply test/e2e/run_privileged_test.go]: I mean most of these test never work anywhere else but linux so I don't think it would matter in practise.

I get your point about consistency, I am certainly ok with your current approach as well. Though looking at the test cases below I am unsatisfied with what they check since they never check for the actual 0 or 1 value. They just check that the values differ meaning this would still pass if we flip the options meaning which is not good.

So I think it would be nice if you could convert the test check below as well to strings.Fields() and then match `"1"`/"0" respectively.

Comment (ricardobranco777) [reply test/e2e/run_privileged_test.go]: Fixed.

Verification run: https://openqa-assets.opensuse.org/tests/5586444/file/podman_e2e-localintegration.txt

Comment (ricardobranco777) [reply test/e2e/run_privileged_test.go]: CI failed on FreeBSD cross:
https://github.com/containers/podman/pull/27846/checks?check_run_id=59723323831

```
test/e2e/config.go:1: : # github.com/containers/podman/v6/test/e2e [github.com/containers/podman/v6/test/e2e.test]
test/e2e/run_privileged_test.go:142:20: undefined: unix.PrctlRetInt
test/e2e/run_privileged_test.go:142:37: undefined: unix.PR_GET_NO_NEW_PRIVS (typecheck)
```

Comment (ricardobranco777) [reply test/e2e/run_privileged_test.go]: Going back to grep...

Comment (ricardobranco777) [reply test/e2e/run_privileged_test.go]: Verification run: https://openqa.opensuse.org/tests/5586529
