### PR TITLE
Fix a compilation error in pkg/machine/config.go

### PR DESCRIPTION
**Pull request by mtrmac**
Commit c524da252e7220323e27d3f72a00107c165e48c9 has merged the outcome of two individually tested PRs, resulting in a semantic conflict.

[EDIT: that was #21573]

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by edsantiago** [comment]
LGTM

**Comment by mtrmac** [comment]
The change is to add `[NO NEW TESTS NEEDED]`.

https://github.com/containers/podman/pull/21621/checks?check_run_id=21490899704 fails, though, building the HEAD commit. It might be safest to just ignore that failure, rather than disable the check and then risk forgetting to reenable…

**Comment by mheon** [comment]
Force-pushed to fix main. Closing as this is no longer necessary.
