### PR TITLE
[v4.4.1-rhel] Bump runc to 1.2.9, Buildah to v1.29.6

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Addresses CVE-2025-52881, and also CVE-2025-31133 and CVE-2025-52565

Fixes: https://issues.redhat.com/browse/RHEL-126910, https://issues.redhat.com/browse/RHEL-126908, https://issues.redhat.com/browse/OCPBUGS-64908, https://issues.redhat.com/browse/OCPBUGS-64909, https://issues.redhat.com/browse/OCPBUGS-64907

#### Checklist

Ensure you have completed the following checklist for your pull request to be reviewed:

- [x] Certify you wrote the patch or otherwise have the right to pass it on as an open-source patch by signing all
commits. (`git commit -s`). (If needed, use `git commit -s --amend`).  The author email must match
the sign-off email address. See [CONTRIBUTING.md](https://github.com/containers/podman/blob/main/CONTRIBUTING.md#sign-your-prs)
for more information.
- [x] Referenced issues using `Fixes: #00000` in commit message (if applicable)
- [x] [Tests](https://github.com/containers/podman/tree/main/test#readme) have been added/updated (or no tests are needed)
- [x] [Documentation](https://github.com/containers/podman/blob/main/docs/README.md) has been updated (or no documentation changes are needed)
- [x] All commits pass `make validatepr` (format/lint checks)
- [x] [Release note](https://github.com/kubernetes/community/blob/master/contributors/guide/release-notes.md) entered in the section below (or `None` if no user-facing changes)

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

File: go.mod [hunk 1]
```diff
@@ -3,67 +3,67 @@ module github.com/containers/podman/v4
 // N/B: If/when bumping the go version below, please revisit the replaced
 // vendoring of golang.org/x/crypto from the temporary containers/golang-crypto
 // fork.  It's likely a newer official release will successfully build with podman.
-go 1.18
+go 1.22.0
```
Comment (Honny1) [inline go.mod:6]:
```
go: errors parsing go.mod:
/var/tmp/go/src/github.com/containers/podman/go.mod:6: invalid go version '1.22.0': must match format 1.23
```

**Comment by TomSweeneyRedHat** [comment]
@timcoding1988 I'm assuming I need to bump AWS credentials here too?  If not, please holler.
```
�[1;33mActivated AWS CLI for service acount.�[0m

An error occurred (AuthFailure) when calling the DescribeImages operation: AWS was not able to validate the provided access credentials
�[1;31mERROR: Failed to update one or more image timestamps:  fedora-podman-aws-arm64-c6447802205601792�[0m
```

File: go.mod (hunk 1 above)
Comment (TomSweeneyRedHat) [reply go.mod:6]: That darn Zero!  Thanks!

**Comment by timcoding1988** [comment]
> @timcoding1988 I'm assuming I need to bump AWS credentials here too?  If not, please holler.
> 
> ```
> 
> �[1;33mActivated AWS CLI for service acount.�[0m
> 
> 
> 
> An error occurred (AuthFailure) when calling the DescribeImages operation: AWS was not able to validate the provided access credentials
> 
> �[1;31mERROR: Failed to update one or more image timestamps:  fedora-podman-aws-arm64-c6447802205601792�[0m
> 
> ```

@TomSweeneyRedHat correct

**Comment by TomSweeneyRedHat** [comment]
@lsm5 @dashea is this ready to go forward?

**Review by Honny1 — APPROVED** [review]
LGTM. I did a quick check.

**Comment by dashea** [comment]
@lsm5 do you know the status of this PR versus the branch you've been working on?

**Comment by lsm5** [comment]
> @lsm5 do you know the status of this PR versus the branch you've been working on?

I'll update this PR with my updates.

**Comment by cevich** [comment]
Just to double-check, let me see if I can get this through the RHEL build and system tests internally...

**Comment by cevich** [comment]
...getting an rpmbuild compile error for podman, attempting to debug...

**Comment by cevich** [comment]
debug fail :disappointed: Maybe it's not worth holding up this PR?

In either case, what I'm seeing is what appears like a normal rpmbuild but it simply dies at the end:

```
...cut...
github.com/containers/podman/vendor/github.com/containers/common/libimage
github.com/containers/podman/vendor/github.com/containers/buildah/internal/util
github.com/containers/podman/vendor/github.com/containers/buildah/util
github.com/containers/podman/vendor/github.com/containers/buildah/bind
github.com/containers/podman/vendor/github.com/containers/buildah/copier
github.com/containers/podman/vendor/github.com/containers/buildah/internal/parse
github.com/containers/podman/vendor/github.com/containers/buildah/chroot
github.com/containers/podman/vendor/github.com/containers/buildah/pkg/parse
github.com/containers/podman/vendor/github.com/containers/buildah/pkg/cli
github.com/containers/podman/vendor/github.com/containers/buildah
github.com/containers/podman/vendor/github.com/containers/buildah/imagebuildah
error: Bad exit status from /var/tmp/rpm-tmp.wyeZlc (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.wyeZlc (%build)

```

Before the build, I updated all the relevant golang packages up to 1.25.3.  There are no other errors displayed, just a handful of code warnings here and there, nothing that looks serious. So I'm unsure of where to look or what to try to fix it :face_with_diagonal_mouth:

**Comment by cevich** [comment]
Update: Instead of doing an `rpmbuild` on my RHEL 9.2 VM (w/ updated golang), I just tried building directly from the 2e8bce2 source.  This is what I got:

```
[root@cevich-1mt-rhel-9 containers-podman-2e8bce2]# make
fatal: not a git repository (or any of the parent directories): .git
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build \
         \
        -ldflags ' -X github.com/containers/podman/v4/libpod/define.buildInfo=1768507185 -X github.com/containers/podman/v4/libpod/config._installPrefix=/usr/local -X github.com/containers/podman/v4/libpod/config._etcDir=/usr/local/etc -X github.com/containers/podman/v4/pkg/systemd/quadlet._binDir=/usr/local/bin -X github.com/containers/common/pkg/config.additionalHelperBinariesDir= ' \
        -tags " exclude_graphdriver_btrfs btrfs_noversion selinux systemd libsubid exclude_graphdriver_devicemapper seccomp" \
        -o bin/podman ./cmd/podman
# github.com/containers/podman/v4/libpod/define
libpod/define/errors.go:96:19: undefined: util.ErrDetach
# github.com/containers/podman/v4/utils
utils/utils_supported.go:29:23: undefined: cgroups.GetUserConnection
make: *** [Makefile:321: bin/podman] Error 1
[root@cevich-1mt-rhel-9 containers-podman-2e8bce2]# go version
go version go1.25.3 (Red Hat 1.25.3-2.el9) linux/amd64
```

**Comment by cevich** [comment]
Indeed, a `# grep 'ErrDetach' vendor/github.com/containers/common/pkg/util/*` gives nothing.  Hrmmmm.  I tried running `make vendor-in-container` but it didn't change anything.  I'm at a loss why it compiles fine on F41 in CI, but fails on RHEL 9.2 :confused:

**Comment by cevich** [comment]
Ugh, -sigh-, no, silly me, this is all my fault.  I took the top commit ID from the list in github instead of the bottom one (e581a2919).  Sorry for the false alarm and noise.

It's building fine on RHEL 9.2 and I've got the BATS tests running now.

I'm going into the corner to cry while I wait.

Edit: Update, BATS Tests appear to be running fine, 99% passing w/ only one expected failure so far.

**Comment by cevich** [comment]
Final manual results:

- rootless failures:
  - many sigproxy fails (frequent flaker)
  - podman ps --external (exit 0 expected 2)
  - pasta (not present; expected)
- remote rootless:
  - many sigproxy (frequent flaker)
  - podman ps --external (exit 0, expected 2)
remote root:
  - podman-remote: non-default connection
    `# podman-remote --remote ps` (negative test; exit 0, exp. 125)

The multiple `podman ps` failures are a bit troubling, but given the other wise high PASS-rate I'm inclined to ignore them.  So my overall opinion is this LGTM.  Whew!

**Comment by cevich** [comment]
@lsm5 I was working on backporting commits from here to `v4.2.0-rhel` and noticed in the "Fix multiple podman cp issues for podman-remote" commit, there are a bunch of documentation changes not mentioned in the commit.  I'm seeing addition of pages for `podman artifacts` and `podman farm` related, neither of which are supported in v4.4

Would you mind double-checking if these are intended to be in that commit/this PR?

**Comment by lsm5** [comment]
> @lsm5 I was working on backporting commits from here to `v4.2.0-rhel` and noticed in the "Fix multiple podman cp issues for podman-remote" commit, there are a bunch of documentation changes not mentioned in the commit. I'm seeing addition of pages for `podman artifacts` and `podman farm` related, neither of which are supported in v4.4
> 
> Would you mind double-checking if these are intended to be in that commit/this PR?

cleaned up. PTAL.

**Comment by cevich** [comment]
Thanks Lokesh, that looks better now.

**Comment by lsm5** [comment]
fwiw, `podman ps --external` passed consistently for me on RHEL-9.2.0-Nightly compose on testing-farm internal ranch.

**Comment by lsm5** [comment]
@cevich @TomSweeneyRedHat PTAL on taking this further / merging.

**Comment by cevich** [comment]
The changes compile on RHEL 9.2 and at least the local-root system tests pass (except for one very minor SELinux test-code bug I'm ignoring).

The local-rootless system test failed on the SIGPROXY tests (frequent flakers), many pasta tests (environment doesn't support IPv6), and again :thinking: the "podman ps --external".  

The ps external failure is happening right near the end of the test. It's expecting a "buildah created" container (created by special buildah command) to not be removable w/o a "-f", but it gets removed anyway:

```
not ok 115 podman ps --external
# (from function `die' in file ./helpers.bash, line 558,
#  from function `run_podman' in file ./helpers.bash, line 228,
#  in test file ./040-ps.bats, line 147)
#   `run_podman 2 rm "$cid"' failed
# $ podman rm -t 0 --all --force --ignore
...cut...
# $ podman ps --external
# CONTAINER ID  IMAGE                              COMMAND     CREATED
  STATUS      PORTS       NAMES
# 140a22894a2e  quay.io/libpod/testimage:20221018  buildah     Less than a second ago
  Storage                 testimage-working-container
# $ podman rm 140a22894a2e
# 140a22894a2e
# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# #| FAIL: exit code is 0; expected 2
# #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# # [teardown]
# $ podman pod rm -t 0 --all --force --ignore
# $ podman rm -t 0 --all --force --ignore
# $ podman network prune --force
# $ podman volume rm -a -f
```

I'm not entirely familiar with this test, but based on the results when run on RHEL 9.2, it seems like either:

1. The earlier `run_podman image prune -f --external` is removing the wrong image.
2. The test or code is broken somehow when podman is run rootless - note: The rootful test passed fine.
3. The rootless `run_podman 2 rm "$cid"` really should be failing but isn't.

I cannot explain why this would pass on Fedora and fail on RHEL :confused:  @lsm5 are your Fedora tests running the rootless podman varient?  Could the "missing DB" changes have unintentionally altered this behavior?  Something else?

**Comment by cevich** [comment]
The remote_root test just finished.  Again a minor SELinux failure, and a `not ok 362 podman-remote: non-default connection` failure.  However, I checked the test code and I think this is simply a test bug.  The failure happens right at the end, on the final "--remote ps":

```
...cut...
# [ rc=125 (expected) ]
# # /usr/bin/podman-remote system connection rm defaultconnection
# # /usr/bin/podman-remote system connection rm env-override
# # /usr/bin/podman-remote system connection rm cli-override
# # /usr/bin/podman-remote --remote ps
# CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# #| FAIL: exit code is 0; expected 125
# #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'm not entirely familiar with this test, but I think perhaps this final check should be removed?  It's not clear to me why the default connection should ever fail a `ps`, but maybe again this has something to do with the "missing DB" handling code (seems unlikely)?

**Comment by cevich** [comment]
remote_rootless test finished.  Same sigproxy (ignoring), pasta (ignoring), and (somewhat concerning) `podman ps --external` failures.

---

In conclusion, I'm a bit nervous about the `ps --external` failures.  I found some internal results from an automated test run in Sept. 2025 for `podman-4.4.1-22.el9_2.4`, and the `ps --external` tests passed.

The only other thing that occurred to me is if maybe this failure is actually caused by a regression or incompatibility with buildah.  When I'm running these 9.2 tests, I'm **NOT** updating the buildah package, so perhaps the `run buildah from $IMAGE` (at the beginning of the test) isn't behaving as expected?

**Comment by lsm5** [comment]
> In conclusion, I'm a bit nervous about the `ps --external` failures. I found some internal results from an automated test run in Sept. 2025 for `podman-4.4.1-22.el9_2.4`, and the `ps --external` tests passed.

Is this on 1MT or testing-farm? I have seen it pass consistently on testing-farm `RHEL-9.2.0-Nightly` compose.

**Comment by lsm5** [comment]
pushed another commit. PTAL at the latest.

**Comment by cevich** [comment]
> Is this on 1MT or testing-farm? I have seen it pass consistently on testing-farm RHEL-9.2.0-Nightly compose.

This is on 1MT with the `podman` and `podman-*` packages built from the HEAD commit on this PR.  But, the other container-related bits (like runc and buildah) are stock, whatever is available on 9.2.  This is why I'm wondering if maybe it's simply a compatibility problem (i.e. the test makes a call to `buildah` to setup the container).  That could also explain why you're seeing it pass everywhere else.

**Comment by cevich** [comment]
> pushed another commit. PTAL at the latest.

Ahh okay, great.  I'll run just the local_rootless test and see what difference that makes.

**Comment by cevich** [comment]
Test finished, unfortunately nothing changed, the results are exactly the same.  Since this is otherwise passing in Fedora and this PR is growing long in the tooth, let's just ignore this one test failure for now.  If it becomes a problem later on in the release process, we can always come back to look deeper and/or fix it.  I'm of course open to other opinions as well.

**Comment by TomSweeneyRedHat** [comment]
@cevich, could you send a full non-snipped test failure(s) that remain on this branch to @mheon and me, please?

I'm not clear if both of the errors a few comments up are still in play, or only the last one.

**Comment by cevich** [comment]
@TomSweeneyRedHat Sure, my colleague also reproduced the `ps --external` failure while testing https://github.com/containers/podman/pull/27934 the output is exactly the same as what I was seeing.  It's [a different podman version](https://github.com/containers/podman/pull/27934), but same testing environment, and the output is exactly the same to my :eye: 

[podman_ps_external_log.txt](https://github.com/user-attachments/files/24823273/podman_ps_external_log.txt) Note: This was from a run against 5.4, I've lost the results from v4.4.1, but they look essentially the same.

Also here's the remote_root non-default connection failure (I think this might be a test bug):

[non-default_connection_log.txt](https://github.com/user-attachments/files/24823374/non-default_connection_log.txt)

**Comment by TomSweeneyRedHat** [comment]
@cevich it could be Friday afternoon brain, but I'm a little confused by:

```
Sure, my colleague also reproduced the ps --external failure while testing https://github.com/containers/podman/pull/27934 the output is exactly the same as what I was seeing.
```
I thought the testing all passed with the updated patch, or are you thinking/saying we need to backport the commits from 27934 into 4.4.1-rhel too?

**Comment by cevich** [comment]
> I thought the testing all passed with the updated patch

The manual testing did not, it failed the same way on "ps --external".

**Comment by cevich** [comment]
@TomSweeneyRedHat Sorry for the confusion, the results I posted here were from Chinmayee's manual testing for RHEL-141490 (podman 5.4).  I lost my results from my 4.4.1 testing, but the output is basically the same by my :eye: (sans line numbers).  Lokesh said this tests pass in [his RHEL testing-farm runs](https://github.com/containers/podman/pull/27764#issuecomment-3768804687).  That's why I think we can ignore it as some odd artifact of how or the environment in which we're manually running the tests.

**Comment by TomSweeneyRedHat** [comment]
@mheon ping

**Comment by cevich** [comment]
Another thing:  For us, it's always the rootless version of the test that fails.  The rootful test (both local and remote) always pass.

**Comment by lsm5** [comment]
I'll try this on 1MT tomorrow. Couldn't reproduce this at all on testing-farm.

File: test/system/040-ps.bats [hunk 2]
```diff
@@ -89,25 +89,38 @@ load helpers
...
 
     run_podman ps -a
     is "${#lines[@]}" "1" "podman ps -a does not see buildah containers"
 
     run_podman ps --external
     is "${#lines[@]}" "3" "podman ps -a --external sees buildah containers"
+    # output can include "second ago" or "seconds ago" depending on the timing so match both
     is "${lines[1]}" \
-       "[0-9a-f]\{12\} \+$IMAGE *buildah .* seconds ago .* Storage .* ${PODMAN_TEST_IMAGE_NAME}-working-container" \
+       "[0-9a-f]\{12\} \+$IMAGE *buildah .* seconds\? ago .* Storage .* ${PODMAN_TEST_IMAGE_NAME}-working-container" \
```
Comment (Luap99) [inline test/system/040-ps.bats:123]: Why is this backported? That seems totally unrelated to the point of runc backports like many other patches in here?
If that test causes failures than maybe not change it in the backport?

**Review by Luap99 — COMMENTED** [review]
I know this is not exactly useful but I am quite surprised with what is being backported here, bumping c/common from v0.51.4 to v0.57.7 feels unreasonable.

I assume this is for the runc CVE fixes? I don't see how bumping common 6 versions can be considered acceptable, the amount of changes are have noting to do with a simple patch the CVE anymore which means this instead risks a ton of other new bugs/regression we cannot account for, especially not if we cherry-pick so many patches that have never been run in such form anywhere upstream, so this is complete frankenstein podman where we cannot guarantee anything IMO.

There are a lot of common changes in that alter the beahvior (sure many bug fixes) but also features and more and I would naturally assume new bugs as well. Introducing them all in a z stream backport does not like a good plane to me?!

**Comment by lsm5** [comment]
> I know this is not exactly useful but I am quite surprised with what is being backported here, bumping c/common from v0.51.4 to v0.57.7 feels unreasonable.

Caused by [buildah v1.29.5](https://github.com/containers/buildah/blob/v1.29.5/go.mod#L8) -> [buildah v1.29.6](https://github.com/containers/buildah/blob/v1.29.6/go.mod#L8) .

**Comment by lsm5** [comment]
Tested on 1MT compose `1MT-RHEL-9.2.0-updates-20251202.0` .  Both `make localsystem` and `make remotesystem` worked for rootless, 2 runs each.

@cevich you got a reproducer for the manual run ?

**Comment by Luap99** [comment]
> > I know this is not exactly useful but I am quite surprised with what is being backported here, bumping c/common from v0.51.4 to v0.57.7 feels unreasonable.
> 
> Caused by [buildah v1.29.5](https://github.com/containers/buildah/blob/v1.29.5/go.mod#L8) -> [buildah v1.29.6](https://github.com/containers/buildah/blob/v1.29.6/go.mod#L8) .

Fair enough, but bumping common over there does not make any more reasonable to me and I think should not have been done there (I don't know why it was done and I don't have the time to look). But I guess it means you already shipping buildah like that? And it is not just common but image and storage too which well means this really ends up being a total frankenstein release with mixing libraries that where never planned for this podman version.


Testing wise did you run *all* upstream test suites, like if there is such a big mixing going on I would not trust system tests only but rather expect all tests suites to pass, i.e. apiv2, compose, e2e and more, but even that would not mean there aren't any unexpected issues.

Anyhow I guess I should just shut up and look the other way, I am not assigned for this work and I think this input is not helpful at this point.

**Comment by lsm5** [comment]
@TomSweeneyRedHat can correct me, but IIUC, the runc maintainers didn't wanna backport the fixes to the existing runc on this branch. And I'd be surprised if we're NOT shipping that updated buildah.

I totally hear you on the library bumps and I had raised that concern with Tom before, but I guess the alternative would be we try to backport patches ourselves to the current runc OR we just bump podman to the version that's known to work with these library versions.

I haven't run the other tests myself, but I'll give it a go. Don't know if SE has run them already.

**Comment by cevich** [comment]
> the alternative would be we try to backport patches ourselves to the current runc 

Kir Kolyshkin attempted this and gave up because of complexity and it was getting too huge and unreasonable.  The earliest version he was able to do was 1.2.5, but a bunch of regressions were hauled in, so now we're on 1.2.9 as the earliest he's willing to support.

Also keep in mind that several of the CVEs addressed here (along with the runc update) require a massive golang bump.  Just supporting that required a host of changes.  So yes, this is a Frankenstein's Monster, and and yes it would be nice to perfectly test everything. But possibly/likely not very practical to try and revive CI on this branch(?).

Though perhaps some select e2e tests could be executed manually? Maybe they still work?

> @cevich you got a reproducer for the manual run ?

@lsm5 yes.  Take a look at the gating plan in dist-git -- It has instructions on running it manually. You just need to stick the final commit ID from this PR into the spec file (no need to commit the change if using `tmt`).  I'll message you the grotesquely long command line because you also need to pass in all the URLs to every required golang 1.25.3 package so it can compile properly :sob:

**Comment by cevich** [comment]
> Tested on 1MT compose 1MT-RHEL-9.2.0-updates-20251202.0 . Both make localsystem and make remotesystem worked for rootless, 2 runs each.

Thanks for confirming, again this is my main reasoning for thinking this is a problem with our testing environment.  Some possibly significant points:

- I'm building podman with golang 1.25.3.
- I'm not updating buildah (it's pre-runc fix)
- Podman is using crun not runc (not sure that matters for this test?).

**Comment by Luap99** [comment]
> I'm not updating buildah (it's pre-runc fix)

I guess that must be it, the test calls buildah to create the external container, as we know our library versions must be in sync generally so expect weird things to happen if you mix them on live systems.

--- 

>     the alternative would be we try to backport patches ourselves to the current runc

Well updating runc is one thing and rebasing that sure I get that part, fine. Where I fail to follow is why we decided that this means we bumping common, image and storage as well? But anyhow ignore my complaints as it is to late for them.

**Comment by cevich** [comment]
> library versions must be in sync generally so expect weird things to happen if you mix them on live systems.

Thanks for your feedback, I too am uneasy at the misalignment of all the parts.  I don't have a RHEL build for 9.2 Buildah with the runc fixes, but I have all the pieces to make that happen.  Let me work on putting that together than I can properly test this.  I don't have a strong opinion on whether or not that testing should block this PR.

**Comment by TomSweeneyRedHat** [comment]
@Luap99 I'm not sure of the exact need, but what drove the bump of common and friends was this commit, ["Update github.com/containers/image/v5 to get updated docker-daemon:"](https://github.com/containers/buildah/pull/6538/commits/4f6e12d5e2944ec8653692fcf1650d8643d4adc5) in the PR (https://github.com/containers/buildah/pull/6538) that bumped Buildah up for the runc fixes.  Nalin and Chris were trying to get stuff out under a huge pressure crunch.  I reviewed the commit, but I didn't catch the bump to common and friends.  

I fear the change might have been made just to get the conformance tests working, and we might have been better served not doing that and just changing the tests.  

@nalind or @cevich any further thoughts?  

And Yes, Buildah with those bumps has been released, do we need to reconsider and revert that patch?

**Comment by lsm5** [comment]
Created this draft PR https://github.com/containers/podman/pull/27987 with fixes for `make localintegration`. Only tried rootful so far. Will try the rest once I get back next week. PTAL.

EDIT: All localintegration tests except checkpoint should pass with this draft branch. :crossed_fingers:

**Comment by cevich** [comment]
> I fear the change might have been made just to get the conformance tests working,

My recollection was, it was _necessary_ for the conformance tests, as in they were formerly (correctly) reporting non-conformance w/ docker if omitted.  Nalin probably remembers better/has more details.

**Comment by nalind** [comment]
As Tom noted, the change was needed to even allow the conformance tests to run - using the docker-daemon: transport to communicate with dockerd is part of how they examine the results of a build done by dockerd for comparison against one built using the buildah library calls.

**Comment by cevich** [comment]
Cross-posting my update from #27987 :

I just did what I probably should have done earlier: Run the commands in the test by hand.  The result: **It passes!**

[manual_ps_external.txt](https://github.com/user-attachments/files/24947377/manual_ps_external.txt)

All I did was:

1. Stop the automation right before it executed the tests
2. ssh in as root, create "testuser1234"
3. ssh in as testuser1234
4. run the equivalent commands from the test, one by one.

So I'm even more convinced that podman and buildah are fine, it's just the way I'm running our tests (or the environment) that's (somehow) the problem.  I'm okay with leaving that up to future-me to investigate and fix.

**Comment by TomSweeneyRedHat** [comment]
This was replace by https://github.com/containers/podman/pull/27987 from @lsm5.  Closing
