### ISSUE TITLE
shadow-4.10 changed libsubid abi

### ISSUE THREAD

**Issue by gyakovlev** [containers/podman#12654]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
https://github.com/shadow-maint/shadow/commit/32f641b207f6ddff1460a22fdc654def4a9c473d#diff-e14258ca4078ba3372fd32b8faf2e0eb74c97e125f8e44e4482ce62816ebe6cc
above commit changed symbol names
so libuid test in
https://github.com/containers/podman/commit/db60a1e654d2212fcc36145cf5e4ba0dd74ce622
no longer works with `shadow-4.10`

```c
$ cat t.c 
#include <shadow/subid.h>
#include <stdlib.h>
int main() {
        struct subid_range *ranges = NULL;
        get_subuid_ranges("root", &ranges);
        free(ranges);
        return 0;
}
```

```shell-session
$ cc -lsubid  t.c
t.c: In function 'main':
t.c:5:9: warning: implicit declaration of function 'get_subuid_ranges' [-Wimplicit-function-declaration]
    5 |         get_subuid_ranges("root", &ranges);
      |         ^~~~~~~~~~~~~~~~~
/usr/lib/gcc/powerpc64le-unknown-linux-gnu/11.2.0/../../../../powerpc64le-unknown-linux-gnu/bin/ld: /tmp/cctUPOHx.o: in function `main':
t.c:(.text+0x40): undefined reference to `get_subuid_ranges'
/usr/lib/gcc/powerpc64le-unknown-linux-gnu/11.2.0/../../../../powerpc64le-unknown-linux-gnu/bin/ld: /usr/lib/gcc/powerpc64le-unknown-linux-gnu/11.2.0/../../../../lib64/libsubid.so: undefined reference to `Prog'
/usr/lib/gcc/powerpc64le-unknown-linux-gnu/11.2.0/../../../../powerpc64le-unknown-linux-gnu/bin/ld: /usr/lib/gcc/powerpc64le-unknown-linux-gnu/11.2.0/../../../../lib64/libsubid.so: undefined reference to `shadow_logfd'
collect2: error: ld returned 1 exit status
```
**Steps to reproduce the issue:**

1. build podman with shadow-4.10

**Describe the results you received:**
podman binary is not linked to libuid.so

**Describe the results you expected:**

links to libuid properly if found

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.5
Built:        Sun Dec 19 19:21:59 2021
OS/Arch:      linux/ppc64le
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No (irrelevant)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by giuseppe** [comment]
thanks for opening an issue.

The PR to fix it is here: https://github.com/containers/podman/pull/12655
