### PR TITLE
[v3.4] Bump required go version to 1.15

### PR DESCRIPTION
**Pull request by dcermak**
Podman fails to build with go 1.13 with:
```
vendor/golang.org/x/net/http2/transport.go:417:45: undefined: os.ErrDeadlineExceeded
```
Updating go to 1.15 fixes this issue.

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by vrothberg** [comment]
Can you re-run `make vendor` and commit the changes?  I think you also need to pass the magic `[NO NEW TESTS NEEDED]` string to the commit message.

**Comment by dcermak** [comment]
> > GO111MODULE=on go mod tidy
> > go mod tidy: go.mod file indicates go 1.16, but maximum supported version is 1.15
> 
> Looks like 1.15 is the right version.

Interesting. How did you get this output? It doesn't show up on my system with go 1.18.

**Comment by vrothberg** [comment]
> Interesting. How did you get this output? It doesn't show up on my system with go 1.18.

The failed Fedora 33 job threw that error.

**Review by vrothberg — COMMENTED** [review]
LGTM
@mheon PTAL

**Comment by mheon** [comment]
`         Error: error storing signature for docker.io/library/alpine:latest, sha256:fa93b01658e3a5a1686dc3ae55f170d8de487006fb53a28efcd12ab0710a2e5f: Unusable secret key`

We're going to need the signature-fix PR to land in this branch to fix CI first.

**Comment by mheon** [comment]
Change otherwise LGTM

**Comment by dcermak** [comment]
@vrothberg Done, thanks for the pointer!

**Comment by vrothberg** [comment]
/lgtm
/hold

Thank you, @dcermak !
